set $auth_header "";
if ($http_referer ~* "(cloudrad-mvp-frontend\.vercel\.app|pacs\.167-233-227-144\.nip\.io)") {
    set $auth_header "Basic Y2xvdWRyYWRfcGFjczpDbG91ZFI0ZF9QNGNzX1NlY3VyMyE=";
}
proxy_set_header Authorization $auth_header;
