# Block destructive and mutating HTTP methods from public domain
if ($request_method ~ ^(DELETE|PUT)$) {
    return 403 "Mutating or deleting PACS data via public domain is forbidden";
}

proxy_set_header Authorization "Basic Y2xvdWRyYWRfcGFjczpDbG91ZFI0ZF9QNGNzX1NlY3VyMyE=";
